### 	gorm.Model
	Name        string `gorm:"not null"`
	Section		string `gorm:"not null"`
	Religiion   string `gorm:"not null"`
	Cast        string `gorm:"not null"`
    Email       string `gorm:"not null"`
	Height      int    `gorm:"not null"`
	Job         string
	JobType     string
	Preferences string
	Phone1      string
	Phone2      string
	Description string `gorm:"not null;type:varchar(255)"`
	Age         int    `gorm:"not null"`
	Education   string `gorm:"not null"`
	Other       string
	Status      int  `gorm:"not null"`
	User        User `gorm:"not null; foreignKey:ID"`
###

POST http://localhost:8080/ads HTTP/1.1
Content-Type: application/x-www-form-urlencoded

Name=John S Mammen
&Section=Bride Wanted
&Gender=Male
&Religiion=Christian
&Cast=Marthoma
&Email=666@mammen.com
&Height=165
&Job=Architect         
&JobType=Engineer
&Preferences=Want a good looking girl
&Phone1=1311323
&Phone2=9999999      
&Description=This is a text of the ad
&Age=44
&Education=BSC EE
&Status=0
&UserID=1

###

GET http://localhost:8080/ads HTTP/1.1

###
GET http://localhost:8080/ads/2 HTTP/1.1
