###
POST http://localhost:8080/users HTTP/1.1
Content-Type: application/x-www-form-urlencoded

Name=John
&Password=4444
&Email=4444@mammen.com
###

GET http://localhost:8080/users HTTP/1.1
###



PATCH  http://localhost:8080/users HTTP/1.1
Content-Type: application/x-www-form-urlencoded

ID=2
&Name=John
&Password=9999
&Email=22@mammen.com

###

PATCH  http://localhost:8080/users HTTP/1.1
Content-Type: application/x-www-form-urlencoded

ID=2
&Password=000
###


DELETE  http://localhost:8080/users/2 HTTP/1.1
###


GET http://localhost:8080/users/2 HTTP/1.1
###