###
POST http://localhost:8080/users HTTP/1.1
Content-Type: application/x-www-form-urlencoded

Username=rose2
&Password=222
&Email=222@email.com
###

GET http://localhost:8080/users HTTP/1.1
###


####
    UID      uuid.UUID `json:"uuid"`
	Username string    `json:"username" binding:"required"`
	Password string    `json:"password" binding:"required"`
	Message  string    `json:"message"`
	Email    string    `json:"email"`
/////
###
PATCH  http://localhost:8080/users HTTP/1.1
Content-Type: application/x-www-form-urlencoded

ID=6
&Username=rose2
&Email=555@email.com

###

PATCH  http://localhost:8080/users HTTP/1.1
Content-Type: application/x-www-form-urlencoded

ID=2
&Email=222@email.com
###


DELETE  http://localhost:8080/users/2 HTTP/1.1
###


GET http://localhost:8080/users/5 HTTP/1.1
###