###
POST http://localhost:8080/users HTTP/1.1
Content-Type: application/x-www-form-urlencoded

Name=John
&Password=5555
&Email=5555@mammen.com
###

GET http://localhost:8080/users HTTP/1.1
###



PATCH  http://localhost:8080/users HTTP/1.1
Content-Type: application/x-www-form-urlencoded

ID=2
&Name=John
&Password=9999
&Email=22@mammen.com

###

PATCH  http://localhost:8080/users HTTP/1.1
Content-Type: application/x-www-form-urlencoded

ID=2
&Password=111
###


DELETE  http://localhost:8080/users/2 HTTP/1.1
###


GET http://localhost:8080/users/5 HTTP/1.1
###